language: node_js

node_js: 
  - 13

services:
  - docker

script:
  
  # Build
  - docker build -t udagram-api-feed:v1 ./udagram-api-feed
  - docker build -t udagram-api-user:v1 ./udagram-api-user
  - docker build -t udagram-frontend:v4 ./udagram-frontend
  - docker build -t reverseproxy:v1 ./udagram-reverseproxy  

  # Tagging
  - docker tag udagram-api-feed:v1 tunv1712/udagram-api-feed:v1
  - docker tag udagram-api-user:v1 tunv1712/udagram-api-user:v1
  - docker tag udagram-frontend:v4 tunv1712/udagram-frontend:v4
  - docker tag reverseproxy:v1 tunv1712/reverseproxy:v1

  - echo 'DOCKER IMAGE LS'
  - docker image ls
after_success:
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - echo 'username, password'  $DOCKER_USERNAME $DOCKER_PASSWORD
  - docker push tunv1712/udagram-api-feed:v1
  - docker push tunv1712/udagram-api-user:v1
  - docker push tunv1712/udagram-frontend:v4
  - docker push tunv1712/reverseproxy:v1

  - echo 'DONE'