language: node_js

node_js: 
  - 13

services:
  - docker

script:
  
  # Build
  - docker build -t udagram-api-feed:v3 ./udagram-api-feed
  - docker build -t udagram-api-user:v3 ./udagram-api-user
  - docker build -t udagram-frontend:v3 ./udagram-frontend
  - docker build -t reverseproxy:v3 ./udagram-reverseproxy  

  # Tagging
  - docker tag udagram-api-feed:v3 tunv1712/udagram-api-feed:v3
  - docker tag udagram-api-user:v3 tunv1712/udagram-api-user:v3
  - docker tag udagram-frontend:v3 tunv1712/udagram-frontend:v3
  - docker tag reverseproxy:v3 tunv1712/reverseproxy:v3
after_success:
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  # Login Docker  

  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  # Pushing 
  - docker push tunv1712/udagram-api-feed:v3
  - docker push tunv1712/udagram-api-user:v3
  - docker push tunv1712/udagram-frontend:v3
  - docker push tunv1712/reverseproxy:v3