apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: W2RlZmF1bHRdDQoNCmF3c19hY2Nlc3Nfa2V5X2lkPUFLSUE1UURFTFpHQzdWVUlXUktFDQoNCmF3c19zZWNyZXRfYWNjZXNzX2tleT05N2w4M3BYc1hwMnI5RGNpMFZqZjM4THhvYjRsdEZBb29JaHBPRU9FDQo=